### ISSUE TITLE
available versions not implemented but used in demo notebook

### ISSUE THREAD

**Issue by RolfHut** [eWaterCycle/ewatercycle-marrmot#1]
See screenshot. Run on eWaterCycle research cloud machine running version 2.0.0 of eWaterCycle.

downloaded the demo notebook and downloaded the demo forcing data.
 
![Screenshot 2023-10-31 at 09 14 37](https://github.com/eWaterCycle/ewatercycle-marrmot/assets/3808328/0389dfda-6e64-471a-af7d-7f882214f250)

**Comment by BSchilperoort** [comment]
The available versions method is indeed gone. Versions are now retrieved from the container image. If a user wants to use a different version of the model, they can specify the container image like this:

```py
from ewatercycle.container import ContainerImage

ewatercycle.models.MarrmotM14(
    forcing=forcing,
    bmi_image=ContainerImage("ewatercycle/marrmot-grpc4bmi:2020.11")  # change the tag to a different version
)
```

This explanation has been added to the notebooks in #4
