### ISSUE TITLE
forcing.sources["MarrmotForcing"] doesn't work with dict for forcing_info

### ISSUE THREAD

**Issue by RolfHut** [eWaterCycle/ewatercycle-marrmot#2]
When running the demo notebooks (tested for both M01 and M14), the use of a dict "forcing_info" does not update / influence the forcing_file mentioned in the dict. In the notebook in this repo, the output of ```print(forcing)``` is also very different.

No errors are thrown however.
See screenshot and compare to https://github.com/eWaterCycle/ewatercycle-marrmot/blob/main/docs/MarrmotM01.ipynb 

![Screenshot 2023-10-31 at 09 27 02](https://github.com/eWaterCycle/ewatercycle-marrmot/assets/3808328/7910cd2a-2c27-4da0-87c6-337efc30aa8f)

**Comment by BSchilperoort** [comment]
Hi Rolf, thanks for raising this issue. The forcing file is now directly passed as a keyword argument. I have updated the notebook in #4 to fix this.
